services:
  app:
    image: serversideup/php:8.4-unit
    container_name: pipl_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - PUID=1000
      - PGID=1000
    ports:
      - "8888:8080"
    volumes:
      - ./:/var/www/html
    networks:
      - pipl_net

networks:
  pipl_net:
    driver: bridge
